import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import classNames from "classnames/bind";
import styles from "./layout.module.scss";

const inter = Inter({ subsets: ["latin"] });
const cn = classNames.bind(styles);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={cn("navigation")}>
          <h1 className={cn("title")}>이름뭐하지</h1>
          <Link href="/">Main</Link>
          <Link href="/test">Test</Link>
        </nav>
        <div className={cn("content")}>{children}</div>
      </body>
    </html>
  );
}
