import "./global.scss";

import classNames from "classnames/bind";
import type { Metadata } from "next";

import WithQuery from "./(with-query)/WithQuery";
import styles from "./layout.module.scss";

const cn = classNames.bind(styles);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={cn("content")}>
          <WithQuery>{children}</WithQuery>
        </main>
      </body>
    </html>
  );
}
