import type { Metadata } from "next";
import classNames from "classnames/bind";
import "./global.scss";
import styles from "./layout.module.scss";

const cn = classNames.bind(styles);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={cn("content")}>{children}</main>
      </body>
    </html>
  );
}
